# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano_v2
    shield: corne_left
    keymap: corne_test
    
  - board: nice_nano_v2
    shield: corne_right
    keymap: corne_test  # Ключевое добавление
    
  - board: nice_nano_v2
    shield: settings_reset
